In [1]:
import numpy as np
import pandas as pd

In [2]:
df=pd.read_csv(r"C:\Users\niles\OneDrive\Documents\Desktop\IMDB Dataset.csv")

In [3]:
df.head()

                                              review sentiment
0  One of the other reviewers has mentioned that ...  positive
1  A wonderful little production. <br /><br />The...  positive
2  I thought this was a wonderful way to spend ti...  positive
3  Basically there's a family where a little boy ...  negative
4  Petter Mattei's "Love in the Time of Money" is...  positive

In [4]:
df=df.iloc[:10000]

In [5]:
df.head()

                                              review sentiment
0  One of the other reviewers has mentioned that ...  positive
1  A wonderful little production. <br /><br />The...  positive
2  I thought this was a wonderful way to spend ti...  positive
3  Basically there's a family where a little boy ...  negative
4  Petter Mattei's "Love in the Time of Money" is...  positive

In [6]:
df['review'].value_counts()

review
Beautiful film, pure Cassavetes style. Gena Rowland gives a stunning performance of a declining actress, dealing with success, aging, loneliness...and alcoholism. She tries to escape her own subconscious ghosts, embodied by the death spectre of a young girl. Acceptance of oneself, of human condition, though its overall difficulties, is the real purpose of the film. The parallel between the theatrical sequences and the film itself are puzzling: it's like if the stage became a way out for the Heroin. If all american movies could only be that top-quality, dealing with human relations on an adult level, not trying to infantilize and standardize feelings... One of the best dramas ever. 10/10.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     2
I have always been a huge fan of "Homicide: Life On The Street" so when I heard there was a reunion movie coming up, I couldn't wait.<br /><br />Let me just say, I was not disappointed at all. It was one of the most powerful 2 hours of television I've ever seen. It was great to see everyone back again, but the biggest pleasure of all was to have Andre Braugher back, because the relationship between Pembleton and Bayliss was always the strongest part of an all-together great show.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         2
This is one of those star-filled over-the-top comedies that could a) be hysterical, or b) wish that you had gone to the dentist to have all your teeth pulled instead. Unfortunately, One Night at McCool's is a classic "b."<br /><br />Goldie Hawn recently commented about "Town and Country" that it's a big problem in Hollywood that they start with hiring the actors and putting together a deal before a script is completed. You have to figure that not only did they go into this picture without a complete script, they also mangled it daily. Maybe we need to send cards and letters to the heads of all the studio that say, "It's the script, stupid." <br /><br />This is also one of those movies where you find yourself feeling sorry for the actors most of the way through. They're working their asses off trying to make all this seem hysterical, but they know most of it is going to be accompanied not by belly laughs but by the sounds of the crickets you can hear inside the silent theatre.<br /><br />Is it an unmitigated disaster? Not entirely. There are some smiles along the way, mostly due to the efforts of the actors. I probably would have gone out of the theatre thinking, "Eh. It was okay." So why the undeniably hostile tone in my review? The ending. If, as it's been noted, the rest of the movie is just all a setup for the ending, then it misses spectacularly. I really wish I could speak specifically about it, but I hate people who give too much away (even in warning). Suffice it to say that as soon as you see John Goodman behind a bent-over Paul Reiser (nothing given away here. It's in the trailer), get the hell out of the theatre and go out thinking, "Eh. It was okay." The rest of the movie is tacked-on and creatively bankrupt. And you'll be appalled that there will actually be people laughing at this mess. <br /><br />If you loved "There's Something About Mary" or "Meet The Parents" (both GREAT movies), then don't bother to see this movie. Go have those teeth taken care of instead.    2
This movie has made me upset! When I think of Cat in the hat. Im thinking of cat in the hat books. You know, the one from a few years back that parents read to thier children. Well, I though that this movie would be a lot like that! But much to my suprise was nothing like the books! Insted it is more like young adult humor movie. In one part cat is talking to a gardening tool (hoe) cat talks to it like it is his hoe (agin adult humor). the naming of his car I all so though was a little untastful for a kids movie. under the rating you'll find: mild cude humor and some double-entendres. I think in short this means adult humor. I wish I could return this movie! wal-mart said they wouldn't because the movie has been opened. If you are thinking about buying this I suggest that maybe rent before you buy.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    2
Sigh. I'm baffled when I see a short like this get attention and assignments and whatnot. I saw this film at a festival before the filmmaker got any attention and forgot about it immediately afterwards. It was mildly annoying to see it swiping the Grinch Who Stole Christmas heart gag along with the narration, the set design seen many times before, the whole weak Tim Burton-ish style, and the story that goes nowhere. And we got the "joke" about shooting the crows with the 45 the first time, alright?<br /><br />But I guess what's really unacceptable is that it even swipes its basic concept from a comic book circa 1999 called LENORE, THE CUTE LITTLE DEAD GIRL by Roman Dirge! As any quick internet search will reveal. I mean, what is this? This is what they base a Hollywood contract on and opens doors in Canada for a filmmaker? "Give your head a shake" as Don Cherry might say.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         2
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            ..
This is the one major problem with this film, along with a good deal of québecois' biggest movies: Done in a pretentious way by pretentious people.<br /><br />It's really sad, but "big shots" movie makers (driving Dodge Stratus...) from this province believes They Got the Thruth, They Know What the Little People Like.<br /><br />We're not a rich province, every time a big movie like this (30 millions?!!?) is made, it's cutting off a lot of others who won't see their movie made because of lack of governmental help. So it generates mediocrity; only movies from "friends of the family" are going to be made.<br /><br />I sound angry and I am. I went see Nouvelle-France expecting a journey in the lives of my ancestors, but i found myself stuck in a pool of inconsistencies: french accent (we gotta please our cousins, so f*** our québecois' language)and lack of historical research is only a few. Add a campy love story and the same music score playing again and again and dumb québecois' viewer is gonna open up and ask for more. I'm glad this pretentious piece of s*** didn't do as planned by the Dodge stratus Big Shots... It's gonna help movie makers who aren't in the very restrained "movie business" of Québec.<br /><br />Rent Cruising Bar instead and have a real good time.<br /><br />PS: I'll never forgive them for ruining such an awesome title.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               1
This Film is the One which you fall in love with. Alfred Hitchcock shall always remain over the top of any directors of his time. The most influential aspects about his films are sheer Simplicity & Gripping Drama. The another best thing about Hitchcock's films is a Definite & Gripping End.<br /><br />Any thing said about "The Man who knew too much" is less. The Cinematography, Acting, Dialogs & Camera Works are magnificent in this Movie. The Song "Que Sera Sera" at the end shall remain in our memories for life time. The film is so enjoyable from start to end that we never know when it ends. Rarely would Hitchcock include humor in his films, this film has comic scenes which fits in to the movie. <br /><br />This film is absolutely brilliant & as good as Vertigo.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          1
Hilarious film, I had a great time watching it. The star (Cuneyt Arkin, sometimes credited as Steve Arkin) is a popular actor from Turkey. He has played in lots of tough-guy roles, epic-sword films, and romances. It was fun to see him with an international cast and some real lousy looking pair of gloves. If I remember it was also dubbed in English which made things even more funnier. (kinda like seeing John Wayne speak Turkish).                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             1

In [7]:
df.isnull().sum()

review       0
sentiment    0
dtype: int64

In [9]:
df.duplicated().sum()

np.int64(17)

In [11]:
df.drop_duplicates(inplace=True)

In [14]:
df.duplicated().sum()

np.int64(0)

In [15]:
import re
def remove_tags(raw_text):
    cleand_text=re.sub(re.compile('<.*?>'),'',raw_text)
    return cleand_text

In [16]:
df['review']=df['review'].apply(remove_tags)

In [17]:
df

                                                 review sentiment
0     One of the other reviewers has mentioned that ...  positive
1     A wonderful little production. The filming tec...  positive
2     I thought this was a wonderful way to spend ti...  positive
3     Basically there's a family where a little boy ...  negative
4     Petter Mattei's "Love in the Time of Money" is...  positive
...                                                 ...       ...
9995  Fun, entertaining movie about WWII German spy ...  positive
9996  Give me a break. How can anyone say that this ...  negative
9997  This movie is a bad movie. But after watching ...  negative
9998  This is a movie that was probably made to ente...  negative
9999  Smashing film about film-making. Shows the int...  positive

[9983 rows x 2 columns]

In [18]:
df['review']=df['review'].apply(lambda x:x.lower())

In [23]:
from nltk.corpus import stopwords
sw_list=stopwords.words('english')
df['review']=df['review'].apply(lambda x: [item for item in  x.split() if item not in sw_list]).apply(lambda x:" ".join(x))

In [24]:
df

                                                 review sentiment
0     one reviewers mentioned watching 1 oz episode ...  positive
1     wonderful little production. filming technique...  positive
2     thought wonderful way spend time hot summer we...  positive
3     basically there's family little boy (jake) thi...  negative
4     petter mattei's "love time money" visually stu...  positive
...                                                 ...       ...
9995  fun, entertaining movie wwii german spy (julie...  positive
9996  give break. anyone say "good hockey movie"? kn...  negative
9997  movie bad movie. watching endless series bad h...  negative
9998  movie probably made entertain middle school, e...  negative
9999  smashing film film-making. shows intense stran...  positive

[9983 rows x 2 columns]

In [27]:
x=df.iloc[:,0:1]
y=df['sentiment']

In [28]:
x

                                                 review
0     one reviewers mentioned watching 1 oz episode ...
1     wonderful little production. filming technique...
2     thought wonderful way spend time hot summer we...
3     basically there's family little boy (jake) thi...
4     petter mattei's "love time money" visually stu...
...                                                 ...
9995  fun, entertaining movie wwii german spy (julie...
9996  give break. anyone say "good hockey movie"? kn...
9997  movie bad movie. watching endless series bad h...
9998  movie probably made entertain middle school, e...
9999  smashing film film-making. shows intense stran...

[9983 rows x 1 columns]

In [29]:
y

0       positive
1       positive
2       positive
3       negative
4       positive
          ...
9995    positive
9996    negative
9997    negative
9998    negative
9999    positive
Name: sentiment, Length: 9983, dtype: object

In [30]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
y=le.fit_transform(y)

In [31]:
y

array([1, 1, 1, ..., 0, 0, 1], shape=(9983,))

In [32]:
from sklearn.model_selection import train_test_split

x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)

In [33]:
x_train.shape

(7986, 1)

In [34]:
from sklearn.feature_extraction.text import CountVectorizer
cv=CountVectorizer()

In [35]:
x_train_bow=cv.fit_transform(x_train['review']).toarray()
x_test_bow=cv.fit_transform(x_test['review']).toarray()

In [36]:
x_train_bow.shape

(7986, 48247)

In [37]:
from sklearn.naive_bayes import GaussianNB
gnb=GaussianNB()
gnb.fit(x_train_bow,y_train)

GaussianNB()

In [40]:
y_pred = gnb.predict(x_test_bow)

from sklearn.metrics import accuracy_score,confusion_matrix
accuracy_score(y_test,y_pred)

ValueError: X has 25538 features, but GaussianNB is expecting 48247 features as input.